### ISSUE TITLE
After setting Brightness the ON Event is also triggered

### ISSUE THREAD

**Issue by jowa0007** [Supereg/homebridge-http-lightbulb#1]
Hi,
I am currently trying to setup my http Lights with homebridge and raspberry pi. I am using this lightbulb plugin and also your notification-server. You did great work there...thank you very much for that! 
I am currently having trouble with setting the brightness on my LED-Spots. After setting the brightness  I also receive an ON Event and the Spots will always turn 100%, since this is my ON-Url-Setup.

I am not sure if it would do the fix but is it possible to NOT set the ON-Characteristic if Brightness is set?

I would be ver happy if you would look into it. Thanks!

**Comment by bauer-andreas** [comment]
You should definitely be able to set the brightness without setting the light to turn On. So technically it works, however I think the home app does turn the lamp on when you change the brightness, but I’m not 100 percent sure about that.

How do you set the brightness? Through the Home App?

**Comment by jowa0007** [comment]
Yes via Home-App. This also happens if I set the brightness via Siri. If I use the slider and change the brightness up and down I get a lot of mixed Brightness and On Events and sometimes the last one is a Brightness Event.

**Comment by bauer-andreas** [comment]
Sorry for not responding for a pretty long time. I didn't have time to test it myself. I'm trying to get my head behind it soon. :)

**Comment by jowa0007** [comment]
Thanks...I was on holidays as well :)

**Comment by bauer-andreas** [comment]
Okay so I looked more into this and it looks like at every brightness request the Home App automatically sends an ON request every time

**Comment by bauer-andreas** [comment]
So today I launched v1.0.0 with many new features. One of those is the new property `withholdPowerUpdate` in the `brightness` object. If set to true the plugin will prevent any requests like mentioned. A more detailed explanation can be found in the README

**Comment by jowa0007** [comment]
Hi...this sound great. I will test it as soon as possible. Thanks for your work!
