### ISSUE TITLE
New category: window coverings

### ISSUE THREAD

**Issue by alexkoenigs** [Supereg/homebridge-http-lightbulb#12]
Hi, I saw you already did a bunch of device categories, so I was wondering if window coverings are anywhere on the roadmap, as i happen to have a bunch of em that I can control via a http server, but I'm not able to make my own plugin.
Thanks!

**Comment by bauer-andreas** [comment]
Once I had a plan to create a window plugin (and window coverings wouldn't be that different). However it it pretty hard to map those types of services in such a way, that they can be applied to any arbitrary use case.
So no, I don't have a plan to support something like that, sorry.
