### ISSUE TITLE
Issue parsing 'On' status response body

### ISSUE THREAD

**Issue by mabiste** [Supereg/homebridge-http-lightbulb#3]
Hey Andi,

first of all, thank you very much for your great plugins! I'm using them together with the http-notification-server which is very nice!

Currently, I have an issue with parsing the 'On' status of the light bulb from statusUrl response body.

When I request the On status I get a JSON body like this one:
> {"LL": { "control": "dev/sps/io/LK207001/state", "value": "1", "Code": "200"}}

-> "value" is "1" when the light is on and "0" when the light is off

I've set the statusPattern to \"value\":\s\"(-?[0-9]):
> "statusPattern": "\\\"value\\\":\\s\\\"(-?[0-9])"

...and tested it on https://regex101.com with my response body:
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/5878397/72192667-cfdc7080-3406-11ea-9d76-6eb350ff2e5c.png">
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/5878397/72192728-e97db800-3406-11ea-8576-fbc1cc9e72cb.png">

But when I open my Home app on my iPhone, I always get the light 'On' status is 'on'. On the debug log I can see the right status on the response body (value = "0"), but it was parsed as 'ON'':
> getPowerState() request returned successfully (200). Body: '{"LL": { "control": "dev/sps/io/LK207001/state", "value": "0", "Code": "200"}}
> getPowerState() power is currently ON

Can you tell me what's wrong? Thank you!

Kind regards!
Marco

**Comment by mabiste** [comment]
Must I have as result of the regex compilation just a 'Full match' like the [example](https://github.com/Supereg/homebridge-http-switch#examples-for-custom-statuspatterns) referenzed on the readme.md of [homebridge-http-switch](https://github.com/Supereg/homebridge-http-switch)?
![grafik](https://user-images.githubusercontent.com/5878397/72225759-646edc00-3589-11ea-8ba5-eecf83c002d7.png)
Or as the exmaple on your [comment](https://github.com/Supereg/homebridge-http-switch/issues/35#issuecomment-499630564) to issue #35 ([Cannot read stare from status url](https://github.com/Supereg/homebridge-http-switch/issues/35)) of the [homebridge-http-switch](https://github.com/Supereg/homebridge-http-switch) plugin?
![grafik](https://user-images.githubusercontent.com/5878397/72225786-b283df80-3589-11ea-9108-5bb7eefaae10.png)

**Comment by mabiste** [comment]
Yes, I've solved the problem by using this statusPattern:
> \"value\":\s\"1\"

With this pattern, I just get a 'Full match' when _value_ is "1":
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/5878397/72225945-a8fb7700-358b-11ea-973f-77a102f6e2d1.png">

When the _value_ is "0", I get no match:
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/5878397/72225962-cb8d9000-358b-11ea-9ad7-6e4610f57347.png">

And also on the debug log I can see correct parsing:
> getPowerState() request returned successfully (200). Body: '{"LL": { "control": "dev/sps/io/LK207001/state", "value": "0", "Code": "200"}}
> getPowerState() power is currently OFF

**Comment by bauer-andreas** [comment]
Great, you already figured it out by yourself 👏 

Regarding your original pattern (`"value":\s"(-?[0-9]):`). The problem here was that you would math any one digit number (`[0-9]`) ad event any negative number (`-?`). The plugin considers anything which matches as ON an and anything that doesn't match as off. This is special for the on characteristic as it only as two states `on` and `off`. So the thing you figured out yourself is the perfect regex for your problem 😃
