### ISSUE TITLE
getPowerState() failed: Parse Error - help please!

### ISSUE THREAD

**Issue by rducky88** [Supereg/homebridge-http-lightbulb#7]
I'm in no doubt that its user error, any help from someone more knowledgable would be greatly appreciated!

The on/off control seems to work but I'm unable to get the current state of the light, the error that shows is:
getPowerState() failed: Parse Error

The statusUrl is:
http://192.168.1.71/cgi-bin/thinlayer.sh?command=AreaMonitor:1,4,7:2,1,2,3,4,5,6,7,8,12,9,10&_=1589054803232

When viewed in a browser it returns this:
A0S0|A1S13:A1C4=60:A1C7=60|A2S0:A2C1=0:A2C2=0:A2C3=0:A2C4=0:A2C5=0:A2C6=0:A2C7=100:A2C8=0:A2C12=0:A2C9=4:A2C10=0

I'm trying to set the statusPattern to match with A2C7=100 which states that the light is on. When off its A2C7=0

I've exhausted the extent of my knowledge and feel like I've tried everything, once again any help would be greatly appreciated! Thanks

**Comment by bauer-andreas** [comment]
A excerpt of your config would be helpful, show what you have tried or rather what you are currently trying.
Is there anything more after this: 'getPowerState() failed: Parse Error' ?

**Comment by bauer-andreas** [comment]
seems to be stale, closing.
