### ISSUE TITLE
Unable to request the status brightness

### ISSUE THREAD

**Issue by ThomB63** [Supereg/homebridge-http-lightbulb#8]
Hello,

First, sorry for my English because I'm French... :)

Thanks for the plugin which is exactly what I want.

I have a problem with requesting the status brightness.
When I launch the url, the result is : { "success": 1, "body":{"last_value": 0} }
The plugin reads only the first "1" which is the same with every request and not read the good value on "last_value".

Have you got an idea for the solution ?

Thanks
Thomas

**Comment by bauer-andreas** [comment]
You would presumably define a custom `statusPattern` for the On characteristic to match your response (as by default it just matches to "1")

a statusPattern like `lastValue": 1` should do it
so the config should look like

```json5
{
  "accessory": "HTTP-LIGHTBULB",
  ...
  "statusPattern": "lastValue\": 1",
  ...
}
```

**Comment by bauer-andreas** [comment]
seems to be stale, closing
